### PR TITLE
Removed option for user to create a custom passphrase.

### PR DESCRIPTION
**Pull request by deleterium**

### CODE REVIEW

**Review by frankTheTank72 — APPROVED** [review]
Quick and dirty 😎

**Review by ohager — APPROVED** [review]
LGTM - wouldn't it be better to also remove the `registerUserDefinedAccount()` from the `BRS` object? Otherwise, unused code is polluting the code base.

**Comment by deleterium** [comment]
> LGTM - wouldn't it be better to also remove the `registerUserDefinedAccount()` from the `BRS` object? Otherwise, unused code is polluting the code base.

This code is not to be updated. I'm adding all new features in neoclassic.

----

By the way, updating the node list as PR from @ipr0310

**Comment by map1336** [comment]
I'll remove `registerUserDefinedAccount()` from the BRS object

**Pull request merged**
